spring:
    application:
        name: ph-security-demo-provider
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

server:
    port: 8701

eureka:
    instance:
    client:
        serviceUrl:
            defaultZone: http://172.18.110.115:8001/eureka/

auth:
  client:
    authHost: http://172.18.110.115:8601/api/authen
    authHeader: access-token