server:
  port: 8604
spring:
  application:
    name: ldap-resource-server
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mysiteforme?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    port: 6379
    host: 127.0.0.1
  thymeleaf:
    content-type: text/html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

eureka:
    instance:
       # statusPageUrlPath: ${management.context-path}/info
       # healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://172.18.110.115:8001/eureka/

security:
  oauth2:
    resource:
      filter-order: 3
      jwt.keyValue: phSecret