spring:
    application:
        name: ph-security-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    port: 8003

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://172.18.110.115:8001/eureka/
auth:
  client:
    clientId: auth-client
    secret: test
    authHeader: access-token
    authHost: http://172.18.110.115:8601/api/authen
    tokenHead: PToken
